### ISSUE TITLE
custom_search_sort.js uses Drupal namespacing, effectively disabling this when the Drupal layer is disabled

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/custom_search#5]
`custom_search_sort.js` uses Drupal namespacing, effectively disabling this when the Drupal layer is disabled. This means you can't add a Custom Search block to a layout when the Drupal compatibility layer disabled.

**Comment by argiepiano** [comment]
PR #6 ready for review.

To test:
1. Disable the Drupal compatibility layer in `settings.php`
2. Enable this module
3. Try to add a Custom Search block to any layout. The JS `custom_search_sort.js` produces an error that prevents the block from being added. Check the browser console to see the error
4. Apply this patch, clear caches and try again. The block should be added without any issue

**Comment by argiepiano** [comment]
@herbdool, this module has no maintainer, and this PR was reviewed (by you) 3 months ago. Would you like to merge on behalf of the bug-squad?

**Comment by herbdool** [comment]
Merged on behalf of the Bug Squad.

**Comment by herbdool** [comment]
Since there's no maintainer I'm going to make a bug fix release.
